# Basic Information 
title: Haolin Fan
position: Research Fellow
affiliation: Nanyang Technological University
affiliation_link: https://www.ntu.edu.sg/mae
affiliation_logo: ./assets/img/ntu.svg
email: haolin.fan@ntu.edu.sg

# Search Engine Optimization (SEO)
keywords: haolin fan, fanhaolin, oliverfan, haolinfan
canonical: https://oliverfanhl.github.io/
description: Haolin Fan is a postdoctoral research fellow at Nanyang Technological University. His research lies in developing autonomous manufacturing systems.

# The option is used to enable the Illinois template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
orcid: https://orcid.org/0000-0002-1808-2660
google_scholar: https://scholar.google.com/citations?user=dVRv_vgAAAAJ&hl=en&inst=3212728378801010220
github_link: https://github.com/OliverFanHL
linkedin: https://www.linkedin.com/in/haolin-fan-526135219
cv_link: https://storage.googleapis.com/post_haolin/CV%20Haolin%20Fan.pdf
# Images 
avatar: https://media.licdn.com/dms/image/v2/D5603AQFfDvq_tbg7Yg/profile-displayphoto-crop_800_800/B56Zx5GuqVJUAM-/0/1771558338413?e=1790208000&v=beta&t=FfKL4WlFiTdu_gXvM_Uf_hQw4gr8fvwJvS1yBptJPgQ

# Footnotes
#footnote: Feel free to use my website's source code.
#footnote_link: https://github.com/yaoyao-liu/minimal-light

# Visitor map
# Public stats page: https://mapmyvisitors.com/web/1c7in
mapmyvisitors_site_id: 1c7in
mapmyvisitors_widget_token: Xj6CuwfZ06R0277UEPHiVlXVLKI7rGyPBNtFswspMC8

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
